name: saarciflex_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  animate_do: ^4.2.0
  shared_preferences: ^2.5.3
  http: ^1.5.0
  flutter_native_splash: ^2.4.6
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  dio: ^5.9.0
  http_parser: ^4.1.2
  path: ^1.9.1
  image: ^4.2.0
  url_launcher: ^6.2.5
  path_provider: ^2.1.5
  open_file: ^3.5.2
  flutter_svg: ^2.0.10
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  fake_async: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/logoSaarCI.png"


# flutter_native_splash.yaml
flutter_native_splash:
  color: "#E53E3E" 
  image: lib/assets/Saar_ip_logo.png
  android_12:
    image: lib/assets/Saar_android12.png
    icon_background_color: "#E53E3E"
  branding_bottom_padding: 32
  web: false
